### ISSUE TITLE
USER STORY: Comment Section

### ISSUE THREAD

**Issue by DFCMK** [DFCMK/My-first-Agile-Project#5]
As a **user** i want **to exchange my thoughts and experiences** so that **I can fit in the local running community and get valuable information and insides about the local running community**

### Acceptance Criteria:
- Comment option for Subscribers only
- build community with giving subscribers option to interact with each other

### Tasks: 
- [ ] Create the comment section
- [ ] Create the comment button for submitting the comment
- [ ] Style the comment box to make it more appealing
