### ISSUE TITLE
USER STORY: Support Desk

### ISSUE THREAD

**Issue by DFCMK** [DFCMK/My-first-Agile-Project#6]
As a **user** i want to be able to  **contact a support team** so that **i can solve my issue**

### Acceptance Criteria:
- Support Desk for subscribers and non subscribers

### Tasks: 
- [ ] Create a support section 
- [ ] Give user option to open a Ticket for live chat communication with a Support Team Member
- [ ] List option how users can get in touch with the Support Team via E-Mail, Phone, Chat
