### ISSUE TITLE
USER STORY: Tombola for new running tracks

### ISSUE THREAD

**Issue by DFCMK** [DFCMK/My-first-Agile-Project#7]
As a **user** i want to be able to **make suggestions for new running tracks** so that **i fell more involved as a valuable memeber of the community**

### Acceptance Criteria:
- Subscribers can upload images with brief descriptions for new running tracks
- Subscribers can vote for uploaded tracks
- The Track which wins brings the subscriber who uploaded the Track a small price.

### Tasks: 
- [ ] Implement a running Track upload section
- [ ] Create a voting section for the user, to be able to vote on uploaded tracks
- [ ] Give Subscriber who uploaded winning track a small price, and inform the user via E-Mail about the winning price
